travis:
  secure:
    BINSTAR_TOKEN: OkXb5gO4gk6X3A0Kfak4na3Q0gI0cvsf8ISoS+sb+0E8oOpkacOqzzQ6RLpe5O6bQkLMOdIGZZOSYu6jj7YullB2Q3If2tpVwOVvNI1boYgRTqzHwvYVsSWjXXWIR6Vnpdh8wxKPz+S5t8zF3ELk8p5qzFV08bWydkljeksmd3X5gQZQp64bcQAiM/4doxAwniPHqL3rYHbh6+A60dr1nUbpNMk1vOW7OQp47v9f9VCwGhL3486XfmoZYJ1wCQzTslJy8ubqiwoZZ05Q/nGL1pb4aIHvxnYpTZTgj466g0gNsrLLW2ekxBVMu8QEfT3qKzQ5dYcenKGGZQHy7Z19kQcAZjKxz9GDOn1blM4uFTKIccm155hCXvkMGstGLx1NgZD120MtDX6BGbvohGK//5k1mhKPB7+8U5VIeeIFn8Sbmk3RlSisqE64J17lZv9vmpzNjhw2TgrajpLseJ+khcYz+JRJPOnkQai14heEeov6fCJsRQk4uYMjJFBZcQVZFhykVMANhFmoavemJwMOCSuCC57+fgEGQOgg9xnVmySI5+IMHgASzYIfBiSpMC2KuNbIjESRiXvh+0/e63Pw5w4smwJu04qVvmb/7Pp6Gzk5Fvy/uVwaqcLb7X385ZntvAeqN4K82TW2K4JVaLVN89w/pVUfUVMErRgjbuM/QyY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
